name: key_value_storage
description: Cross-platform local key-value storage for Fullstack Chat App.
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.13.0 <4.0.0'

resolution: workspace

dependencies:
  meta: ^1.16.0

dev_dependencies:
  lints: ^6.1.0
  test: ^1.25.0
